#!/usr/bin/env bash
# tff from client to server.
# Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY

if [ $# -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

if [ $# -eq 4 ]
then
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
else
    scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
fi
