#!/usr/bin/env bash
# creates a file and displays msgs corresponding to signal
echo $$ > /var/run/myscript.pid
trap 'echo I hate the kill command; rm /var/run/myscript.pid; exit' SIGTERM
trap 'echo Y U no love me?!' SIGINT
trap 'rm /var/run/myscript.pid; exit' SIGQUIT

while true; do
	echo To infinity and beyond
	sleep 2
done
