#!/usr/bin/env bash
# Display "Best School" 10 times
# 9th element display "Best School" and then "Hi"
i=1
while [ $i -le 10 ]
do
	if [ $i = 10 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	i=$(( i + 1 ))
done
