#!/usr/bin/env bash
# loop from 1 to 10 and:
# display bad luck for the 4th element
# display good luck for the 8th element
# display Best School for the other elements
i=1
while [ $i -le 10 ]
do
	if [ $i = 4 ]
	then
		echo "bad luck"
	elif [ $i = 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$(( i + 1 ))
done
