#!/usr/bin/env bash
# a script that sets up the firewall via ufw
# Install UFW
sudo apt update
sudo apt install ufw

# Default rule to deny incoming traffic
sudo ufw default deny incoming

# Allow SSH, HTTPS, and HTTP
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# Enable UFW
sudo ufw enable

# Check UFW status
sudo ufw status
